general:
  project_name: AED_project
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 16
  training_epochs: 50
  optimizer: adam
  initial_learning: 0.001
  patience: 100
  learning_rate_scheduler: reducelronplateau
  restore_best_weights: True

dataset:
  name: custom
  class_names: ['dog', 'laughing', 'crackling_fire', 'helicopter', 'rain',
       'crying_baby', 'clock_tick', 'sneezing', 'rooster','car_horn']
  audio_path: /content/stm32ai-modelzoo/ESC-50/audio
  csv_path: /content/stm32ai-modelzoo/ESC-50/meta/esc50.csv
  file_extension: .wav
  validation_split: 0.1
  test_split : 0.2
  test_path: 
  use_other_class: False
  n_samples_per_other_class: 2

#dataset_specific:
# Contains dataset-specific parameters.
#  fsd50k:
#    csv_folder: datasets/FSD50K/FSD50K.ground_truth
#    dev_audio_folder: datasets/FSD50K/FSD50K.dev_audio
#    eval_audio_folder: datasets/FSD50K/FSD50K.eval_audio
#    audioset_ontology_path: ../utils/dataset_utils/fsd50k/audioset_ontology.json
#    only_keep_monolabel: True


pre_processing:
  min_length: 1
  max_length : 10
  target_rate: 16000
  top_db: 30
  frame_length: 3200
  hop_length: 3200
  trim_last_second: False
  lengthen : 'after'

feature_extraction:
  patch_length: 96
  n_mels: 64
  overlap: 0.25
  n_fft: 512
  hop_length: 160
  window_length: 400
  window: hann
  center: False
  pad_mode: constant
  power: 1.0
  fmin: 125
  fmax: 7500
  norm: None
  htk : True
  to_db : False
  include_last_patch: False

data_augmentation:
  GaussianNoise: 0.1
  VolumeAugment: True
  min_scale: 0.8
  max_scale: 1.2
  SpecAug: False
  freq_mask_param: 1
  time_mask_param: 1
  n_freq_mask: 3
  n_time_mask: 4
  mask_value : 0

model:
  model_type: {name : yamnet, embedding_size: 256}
  # Shape of a single patch.
  # Input shape must be [mels, frames]
  input_shape: [64, 96]
  expand_last_dim: True
  transfer_learning : True
  fine_tune : False
  dropout: 0
  multi_label : False


quantization:
  quantize: True
  evaluate: True
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: int8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  version: 7.3.0
  optimization: balanced
  footprints_on_target: B-U585I-IOT02A
  path_to_stm32ai: False

mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}